/**
 * Relational Seed Data for ABC Hotel & Restaurant
 */
import bcrypt from 'bcryptjs';
import { User, Hotel, Restaurant, DiningTable, MenuCategory, MenuItem } from '../types/index.ts';

export async function getSeedData() {
  // Passwords hashed with bcrypt
  const adminPasswordHash = await bcrypt.hash('Password@123', 10);
  const customerPasswordHash = await bcrypt.hash('Customer@ABC2026!', 10);

  const users: User[] = [
    {
      id: 'usr-admin-001',
      firstName: 'Hotel',
      lastName: 'Admin',
      username: 'admin',
      email: 'admin@gmail.com',
      phone: '+91 9876543210',
      passwordHash: adminPasswordHash,
      role: 'ADMIN',
      status: 'ACTIVE',
      createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
      updatedAt: new Date('2026-01-01T00:00:00Z').toISOString()
    },
    {
      id: 'usr-staff-alias-001',
      firstName: 'Hotel',
      lastName: 'Staff',
      username: 'staff',
      email: 'staff@gmail.com',
      phone: '+91 9876543211',
      passwordHash: adminPasswordHash,
      role: 'STAFF',
      status: 'ACTIVE',
      createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
      updatedAt: new Date('2026-01-01T00:00:00Z').toISOString()
    },
    {
      id: 'usr-kitchen-001',
      firstName: 'Executive',
      lastName: 'Chef & Kitchen',
      username: 'kitchen',
      email: 'kitchen@gmail.com',
      phone: '+91 9876543299',
      passwordHash: adminPasswordHash, // Password@123
      role: 'KITCHEN',
      status: 'ACTIVE',
      createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
      updatedAt: new Date('2026-01-01T00:00:00Z').toISOString()
    },
    {
      id: 'usr-manager-001',
      firstName: 'Hotel',
      lastName: 'Manager',
      username: 'manager',
      email: 'manager@gmail.com',
      phone: '+91 9876543222',
      passwordHash: adminPasswordHash, // Password@123
      role: 'MANAGER',
      status: 'ACTIVE',
      createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
      updatedAt: new Date('2026-01-01T00:00:00Z').toISOString()
    },
    {
      id: 'usr-delivery-001',
      firstName: 'Delivery',
      lastName: 'Staff Rider',
      username: 'delivery',
      email: 'delivery@gmail.com',
      phone: '+91 9876543200',
      passwordHash: adminPasswordHash, // Password@123
      role: 'DELIVERY',
      status: 'ACTIVE',
      createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
      updatedAt: new Date('2026-01-01T00:00:00Z').toISOString()
    },
    {
      id: 'usr-rakesh-001',
      firstName: 'Rakesh',
      lastName: 'Chandh',
      username: 'rakesh.chandh',
      email: 'rakeshchandh1998@gmail.com',
      phone: '+91 9876543201',
      passwordHash: adminPasswordHash, // Password@123
      role: 'CUSTOMER',
      status: 'ACTIVE',
      createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
      updatedAt: new Date('2026-01-01T00:00:00Z').toISOString()
    },
    {
      id: 'usr-demo-cust-001',
      firstName: 'Priya',
      lastName: 'Sharma',
      username: 'customer',
      email: 'customer@gmail.com',
      phone: '+91 9876543290',
      passwordHash: adminPasswordHash, // Password@123
      role: 'CUSTOMER',
      status: 'ACTIVE',
      createdAt: new Date('2026-01-10T10:00:00Z').toISOString(),
      updatedAt: new Date('2026-01-10T10:00:00Z').toISOString()
    }
  ];

  const hotel: Hotel = {
    id: 'htl-abc-001',
    name: 'ABC Hotel & Luxury Suites',
    description: 'A 5-star haven of timeless luxury, world-class gastronomy, and exceptional hospitality nestled in the heart of the city.',
    address: '742 Heritage Promenade, Royal Gardens, Sector 4',
    phone: '+91 22 4987 6543',
    email: 'concierge@abchotel.com',
    createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
    updatedAt: new Date('2026-01-01T00:00:00Z').toISOString()
  };

  const restaurant: Restaurant = {
    id: 'rst-abc-001',
    hotelId: 'htl-abc-001',
    name: 'ABC Restaurant & Fine Dining',
    description: 'Award-winning culinary destination celebrating authentic heritage recipes and innovative global gastronomy by Michelin-acclaimed chefs.',
    openingTime: '09:00',
    closingTime: '23:00',
    status: 'OPEN'
  };

  const tables: DiningTable[] = [
    {
      id: 'tbl-001',
      restaurantId: 'rst-abc-001',
      tableNumber: 'Table 01',
      capacity: 2,
      location: 'Window View',
      status: 'AVAILABLE'
    },
    {
      id: 'tbl-002',
      restaurantId: 'rst-abc-001',
      tableNumber: 'Table 02',
      capacity: 2,
      location: 'Private Booth',
      status: 'AVAILABLE'
    },
    {
      id: 'tbl-003',
      restaurantId: 'rst-abc-001',
      tableNumber: 'Table 03',
      capacity: 4,
      location: 'Center Terrace',
      status: 'AVAILABLE'
    },
    {
      id: 'tbl-004',
      restaurantId: 'rst-abc-001',
      tableNumber: 'Table 04',
      capacity: 4,
      location: 'Garden Side',
      status: 'AVAILABLE'
    },
    {
      id: 'tbl-005',
      restaurantId: 'rst-abc-001',
      tableNumber: 'Table 05',
      capacity: 6,
      location: 'Window View',
      status: 'AVAILABLE'
    },
    {
      id: 'tbl-006',
      restaurantId: 'rst-abc-001',
      tableNumber: 'Table 06',
      capacity: 8,
      location: 'VIP Section',
      status: 'AVAILABLE'
    },
    {
      id: 'tbl-007',
      restaurantId: 'rst-abc-001',
      tableNumber: 'Table 07',
      capacity: 4,
      location: 'Private Booth',
      status: 'AVAILABLE'
    },
    {
      id: 'tbl-008',
      restaurantId: 'rst-abc-001',
      tableNumber: 'Table 08',
      capacity: 2,
      location: 'Garden Side',
      status: 'AVAILABLE'
    }
  ];

  const menuCategories: MenuCategory[] = [
    {
      id: 'cat-001',
      name: 'Starters',
      description: 'Artisanal vegetarian and non-vegetarian appetizers, tandoori grills, and crispy bites.',
      displayOrder: 1,
      status: 'ACTIVE'
    },
    {
      id: 'cat-004',
      name: 'Biryani & Rice',
      description: 'Fragrant Dum biryanis, aromatic saffron basmati, and slow-cooked rice delicacies.',
      displayOrder: 2,
      status: 'ACTIVE'
    },
    {
      id: 'cat-002',
      name: 'Main Course',
      description: 'Rich royal curries, slow-simmered gravies, and exquisite culinary mains.',
      displayOrder: 3,
      status: 'ACTIVE'
    },
    {
      id: 'cat-003',
      name: 'Breads',
      description: 'Fresh clay-oven tandoori rotis, garlic butter naans, and accompaniments.',
      displayOrder: 4,
      status: 'ACTIVE'
    },
    {
      id: 'cat-005',
      name: 'Desserts',
      description: 'Decadent royal Indian sweets, halwas, and signature delicacies.',
      displayOrder: 5,
      status: 'ACTIVE'
    }
  ];

  const menuItems: MenuItem[] = [
    // --------------------------------------------------
    // STARTERS – VEGETARIAN (5 dishes)
    // --------------------------------------------------
    {
      id: 'itm-001',
      sku: 'START-PAN-001',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Paneer Tikka',
      description: 'Char-grilled Indian cottage cheese marinated with hung yogurt and aromatic tandoori spices.',
      price: 280,
      imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 18,
      calories: 360,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-002',
      sku: 'START-GOB-002',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Gobi Manchurian',
      description: 'Crispy fried cauliflower florets tossed in a zesty Indo-Chinese garlic soy glaze.',
      price: 220,
      imageUrl: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 15,
      calories: 280,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: ['Gluten', 'Soy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-003',
      sku: 'START-COR-003',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Crispy Corn',
      description: 'Golden fried sweet corn kernels tossed with fresh scallions, crushed black pepper, and chat masala.',
      price: 240,
      imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'Mild',
      prepTimeMinutes: 12,
      calories: 260,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-004',
      sku: 'START-SRP-004',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Veg Spring Rolls',
      description: 'Crispy golden pastry sheets stuffed with wok-tossed shredded vegetables, served with sweet chilli dip.',
      price: 220,
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'Mild',
      prepTimeMinutes: 15,
      calories: 290,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: ['Gluten'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-005',
      sku: 'START-TRU-005',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Truffle Malai Paneer Tikka',
      description: 'Silken cottage cheese infused with black truffle essence, velvety hung curd, and royal cardamom.',
      price: 340,
      imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'Mild',
      prepTimeMinutes: 18,
      calories: 390,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // --------------------------------------------------
    // STARTERS – NON-VEGETARIAN (5 dishes)
    // --------------------------------------------------
    {
      id: 'itm-006',
      sku: 'START-CHK-006',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Chicken 65',
      description: 'Spicy and crisp deep-fried boneless chicken tempered with curry leaves, mustard seeds, and southern spices.',
      price: 320,
      imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Hot',
      prepTimeMinutes: 18,
      calories: 420,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Eggs'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-007',
      sku: 'START-CHT-007',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Chicken Tikka',
      description: 'Tender chicken fillets marinated in spiced mustard oil and yogurt, roasted to perfection in clay tandoor.',
      price: 360,
      imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 20,
      calories: 450,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-008',
      sku: 'START-WNG-008',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Chicken Wings',
      description: 'Juicy chicken wings glazed in smoky barbecue glaze and aromatic roasted spices.',
      price: 340,
      imageUrl: 'https://images.unsplash.com/photo-1527477378408-1bc0ae05b8da?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 18,
      calories: 480,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-009',
      sku: 'START-MSK-009',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Mutton Seekh Kebab',
      description: 'Minced royal lamb skewers blended with mint, ginger, and garam masala, grilled over charcoal.',
      price: 420,
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Hot',
      prepTimeMinutes: 22,
      calories: 510,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-010',
      sku: 'START-FIS-010',
      categoryId: 'cat-001',
      categoryName: 'Starters',
      name: 'Fish Tikka',
      description: 'Fresh boneless fish steaks marinated with carom seeds, turmeric, and lemon juice, tandoor roasted.',
      price: 420,
      imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 18,
      calories: 340,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Fish', 'Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // --------------------------------------------------
    // BIRYANI & RICE (4 dishes)
    // --------------------------------------------------
    {
      id: 'itm-011',
      sku: 'BRY-CHK-011',
      categoryId: 'cat-004',
      categoryName: 'Biryani & Rice',
      name: 'Chicken Biryani',
      description: 'Fragrant basmati rice layered with tender chicken, herbs, and traditional biryani spices.',
      price: 320,
      imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 25,
      calories: 650,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-012',
      sku: 'BRY-MUT-012',
      categoryId: 'cat-004',
      categoryName: 'Biryani & Rice',
      name: 'Mutton Biryani',
      description: 'Slow-cooked succulent lamb layered with aged saffron basmati rice, caramelized onions, and kewra.',
      price: 420,
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Hot',
      prepTimeMinutes: 28,
      calories: 720,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-013',
      sku: 'BRY-VEG-013',
      categoryId: 'cat-004',
      categoryName: 'Biryani & Rice',
      name: 'Veg Biryani',
      description: 'Aromatic basmati rice layered with garden vegetables, saffron, aromatic herbs, and fried onions.',
      price: 260,
      imageUrl: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 22,
      calories: 490,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-014',
      sku: 'BRY-PAN-014',
      categoryId: 'cat-004',
      categoryName: 'Biryani & Rice',
      name: 'Paneer Biryani',
      description: 'Spiced cottage cheese cubes and long-grain basmati cooked in authentic dum style with mint and saffron.',
      price: 290,
      imageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 22,
      calories: 540,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // --------------------------------------------------
    // MAIN COURSE – VEGETARIAN (4 dishes)
    // --------------------------------------------------
    {
      id: 'itm-015',
      sku: 'MAIN-PBM-015',
      categoryId: 'cat-002',
      categoryName: 'Main Course',
      name: 'Paneer Butter Masala',
      description: 'Cottage cheese simmered in a velvety buttery tomato gravy enriched with fresh cream and dried fenugreek.',
      price: 280,
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'Mild',
      prepTimeMinutes: 20,
      calories: 480,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy', 'Nuts'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-016',
      sku: 'MAIN-DAL-016',
      categoryId: 'cat-002',
      categoryName: 'Main Course',
      name: 'Dal Makhani',
      description: 'Slow-simmered black lentils cooked overnight with butter, cream, and heirloom spices for deep flavor.',
      price: 240,
      imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'Mild',
      prepTimeMinutes: 18,
      calories: 420,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-017',
      sku: 'MAIN-KDP-017',
      categoryId: 'cat-002',
      categoryName: 'Main Course',
      name: 'Kadai Paneer',
      description: 'Paneer cubes tossed with crunchy bell peppers, onions, and freshly pounded coriander-chilli kadai masala.',
      price: 280,
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 20,
      calories: 450,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-018',
      sku: 'MAIN-VEG-018',
      categoryId: 'cat-002',
      categoryName: 'Main Course',
      name: 'Veg Kolhapuri',
      description: 'Assorted garden vegetables cooked in a spicy, fiery Kolhapuri red chilli and roasted coconut gravy.',
      price: 250,
      imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: true,
      spiceLevel: 'Hot',
      prepTimeMinutes: 20,
      calories: 360,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // --------------------------------------------------
    // MAIN COURSE – NON-VEGETARIAN (3 dishes)
    // --------------------------------------------------
    {
      id: 'itm-019',
      sku: 'MAIN-BTC-019',
      categoryId: 'cat-002',
      categoryName: 'Main Course',
      name: 'Butter Chicken',
      description: 'Tender chicken cooked in a rich, creamy tomato and butter gravy.',
      price: 340,
      imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: false,
      spiceLevel: 'Mild',
      prepTimeMinutes: 22,
      calories: 580,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy', 'Nuts'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-020',
      sku: 'MAIN-CTM-020',
      categoryId: 'cat-002',
      categoryName: 'Main Course',
      name: 'Chicken Tikka Masala',
      description: 'Smoked chicken tikka chunks cooked in a spiced onion-tomato gravy with aromatic ginger and bell peppers.',
      price: 360,
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Medium',
      prepTimeMinutes: 22,
      calories: 560,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-021',
      sku: 'MAIN-MRJ-021',
      categoryId: 'cat-002',
      categoryName: 'Main Course',
      name: 'Mutton Rogan Josh',
      description: 'Traditional Kashmiri slow-braised mutton curry flavored with alkanet root, fennel, and aromatic spices.',
      price: 430,
      imageUrl: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=800&auto=format&fit=crop&q=80',
      vegetarian: false,
      type: 'NON_VEGETARIAN',
      spicy: true,
      spiceLevel: 'Hot',
      prepTimeMinutes: 25,
      calories: 620,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // --------------------------------------------------
    // BREADS (2 dishes)
    // --------------------------------------------------
    {
      id: 'itm-022',
      sku: 'BRD-BNA-022',
      categoryId: 'cat-003',
      categoryName: 'Breads',
      name: 'Butter Naan',
      description: 'Soft, pillowy tandoor-baked flatbread brushed generously with fresh melted butter.',
      price: 70,
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'None',
      prepTimeMinutes: 8,
      calories: 180,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: ['Dairy', 'Gluten'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-023',
      sku: 'BRD-GNA-023',
      categoryId: 'cat-003',
      categoryName: 'Breads',
      name: 'Garlic Naan',
      description: 'Soft tandoor-baked naan topped with fresh garlic and butter.',
      price: 90,
      imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'None',
      prepTimeMinutes: 8,
      calories: 200,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: ['Dairy', 'Gluten'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // --------------------------------------------------
    // DESSERTS (2 dishes)
    // --------------------------------------------------
    {
      id: 'itm-024',
      sku: 'DES-GJM-024',
      categoryId: 'cat-005',
      categoryName: 'Desserts',
      name: 'Gulab Jamun',
      description: 'Warm golden fried milk dumplings soaked in cardamom and rose water infused sugar syrup.',
      price: 120,
      imageUrl: 'https://images.unsplash.com/photo-1589119908995-c6837fa14d48?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'None',
      prepTimeMinutes: 5,
      calories: 280,
      available: true,
      isActive: true,
      isChefSpecial: true,
      allergens: ['Dairy', 'Gluten'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'itm-025',
      sku: 'DES-GKH-025',
      categoryId: 'cat-005',
      categoryName: 'Desserts',
      name: 'Gajar Ka Halwa',
      description: 'Traditional slow-cooked dessert made with grated red carrots, whole milk, pure desi ghee, and dry fruits.',
      price: 150,
      imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=80',
      vegetarian: true,
      type: 'VEGETARIAN',
      spicy: false,
      spiceLevel: 'None',
      prepTimeMinutes: 6,
      calories: 320,
      available: true,
      isActive: true,
      isChefSpecial: false,
      allergens: ['Dairy', 'Nuts'],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ];

  return { users, hotel, restaurant, tables, menuCategories, menuItems };
}
